version: '3.9'

services:
  web:
    build: .
    command: gunicorn pet.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - pet/.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: petdb
      POSTGRES_USER: neo
      POSTGRES_PASSWORD: 1234

volumes:
  postgres_data:
